export default {
  LOAD_TODOS: 'LOAD_TODOS',
  LOAD_CARD: 'LOAD_CARD',
  CREATE_CARD: 'CREATE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  UPDATE_CARD: 'UPDATE_CARD',
  CREATE_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  CHECK_TASK: 'CHECK_TASK'
};
